"""create initial tables

Revision ID: 31768bd751de
Revises: 
Create Date: 2026-09-08 10:12:59.899124

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31768bd751de'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mst_department',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('dep_name', sa.String(length=100), nullable=False),
    sa.Column('date_created', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mst_designation',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('designation_name', sa.String(length=15), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('date_created', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mst_holidays',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('holiday_name', sa.String(length=100), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mst_leave_type',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('type_name', sa.String(length=50), nullable=False),
    sa.Column('max_days_per_year', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mst_payroll_setting',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('type', sa.Enum('TAX', 'PF', 'ESI', name='payrollsettingtype'), nullable=False),
    sa.Column('rate_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mst_reference_type',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('type_name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('type_name')
    )
    op.create_table('mst_reference_value',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('reference_type_id', sa.Integer(), nullable=False),
    sa.Column('reference_value', sa.String(length=100), nullable=False),
    sa.Column('sequence_number', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['reference_type_id'], ['mst_reference_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('txn_user',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('dob', sa.Date(), nullable=False),
    sa.Column('gender', sa.Enum('MALE', 'FEMALE', 'OTHER', name='gender'), nullable=True),
    sa.Column('phonenumber', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'EMPLOYEE', name='role'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('dep_id', sa.Integer(), nullable=True),
    sa.Column('designation_id', sa.Integer(), nullable=True),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('employee_code', sa.String(length=30), nullable=False),
    sa.Column('joining_date', sa.Date(), nullable=False),
    sa.Column('employment_type', sa.Enum('FULL_TIME', 'PART_TIME', 'CONTRACT', name='employmenttype'), nullable=False),
    sa.Column('emergency_contact', sa.String(length=20), nullable=False),
    sa.Column('blood_group', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['dep_id'], ['mst_department.id'], ),
    sa.ForeignKeyConstraint(['designation_id'], ['mst_designation.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('employee_code')
    )
    op.create_table('mst_salary_structure',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('basic_salary', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('hra', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('other_allowances', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['txn_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('txn_attendence',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('check_in', sa.Time(), nullable=True),
    sa.Column('check_out', sa.Time(), nullable=True),
    sa.Column('working_hours', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('status', sa.Enum('PRESENT', 'ABSENT', 'HALF_DAY', 'LEAVE', name='attendancestatus'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['txn_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('txn_files',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('document_type', sa.String(length=50), nullable=False),
    sa.Column('file_path', sa.String(length=255), nullable=False),
    sa.Column('uploaded_time', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['txn_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('txn_leave_request',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('leave_type_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='leavestatus'), nullable=False),
    sa.Column('approved', sa.BigInteger(), nullable=True),
    sa.Column('applied_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['approved'], ['txn_user.id'], ),
    sa.ForeignKeyConstraint(['leave_type_id'], ['mst_leave_type.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['txn_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('txn_notifications',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('type', sa.Enum('LEAVE', 'SALARY', 'ATTENDANCE', 'GENERAL', name='notificationtype'), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['txn_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('txn_salary_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('month_year', sa.String(length=7), nullable=False),
    sa.Column('basic_salary', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('allowances', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('deductions', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('tax', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('pf', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('esi', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('lic_deductions', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('net_salary', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('payment_date', sa.Date(), nullable=True),
    sa.Column('payslip_file', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('GENERATED', 'PAID', name='salarystatus'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['txn_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('txn_user_lic',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('policy_number', sa.String(length=50), nullable=False),
    sa.Column('provider', sa.String(length=100), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['txn_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('txn_user_lic')
    op.drop_table('txn_salary_records')
    op.drop_table('txn_notifications')
    op.drop_table('txn_leave_request')
    op.drop_table('txn_files')
    op.drop_table('txn_attendence')
    op.drop_table('mst_salary_structure')
    op.drop_table('txn_user')
    op.drop_table('mst_reference_value')
    op.drop_table('mst_reference_type')
    op.drop_table('mst_payroll_setting')
    op.drop_table('mst_leave_type')
    op.drop_table('mst_holidays')
    op.drop_table('mst_designation')
    op.drop_table('mst_department')
    # ### end Alembic commands ###